---
pool:
  vmImage: ubuntu-latest
  name: "Azure Pipelines"

name: practice
appendCommitMessageToRunName: yes
trigger: 
  - master
parameters:
  - name: testpermaneter 
    displayName: testpermaneter 
    type: string 
    default: v1.0
    values: 
      - v1.0
      - v2.0
steps:
  - task: Docker@2
    inputs:
      command: 'build'
      buildContext: .
      repository: testpractice
      tags: '$(Build.BuildId)'